language: python
python:
  - "3.9-dev"
# command to install dependencies
before_script:
  - pip install -r requirements.txt

install:
  - pip install .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
